version: '3.8'
name: social-media-application

services:
  # Backend service using Spring Boot
  backend:
    image: ${DOCKER_HUB_USERNAME}/social-media-backend:1.0.0
    container_name: backend-application
    build:
      context: ./backend
    ports:
      - 5000:5000
    environment:
      - SPRING_PROFILES_ACTIVE=${ACTIVE_PROFILE}
      - JWT_SECRET=${JWT_SECRET}
      - MONGODB_URI=${MONGODB_URI}
    networks:
      - social-app-network

  # Frontend service using React
  frontend:
    image: ${DOCKER_HUB_USERNAME}/social-media-frontend:1.0.0
    container_name: frontend-application
    build:
      context: ./frontend
    ports:
      - 3000:80
    networks:
      - social-app-network

networks:
  social-app-network:
    driver: bridge

#---------------------------------------------------------------------------------------#

# WHEN SETTING UP LOCALLY, CONFIGURE ${ACTIVE_PROFILE}, ${JWT_SECRET}, AND ${MONGODB_URI}.
# ${DOCKER_HUB_USERNAME} IS NOT NEEDED FOR LOCAL DEVELOPMENT AND CAN BE REMOVED.

#---------------------------------------------------------------------------------------#

# STARTS SERVICES AND REBUILDS THEM IF NEEDED: [ docker-compose up --build ]
# STOPS SERVICES AND REMOVES CONTAINERS, NETWORKS, AND VOLUMES: [ docker-compose down ]

#---------------------------------------------------------------------------------------#