name: Build and Deploy Social Media Application Containers

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/v2.25.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Set up environment variables
      - name: Set up Docker Compose environment
        run: |
          echo "DOCKER_HUB_USERNAME=${{ secrets.DOCKER_HUB_USERNAME }}" >> .env

      # Build and push the frontend image
      - name: Build Frontend Image
        run: |
          docker-compose -f docker-compose.yml build frontend

      - name: Push Frontend Image
        run: |
          docker-compose -f docker-compose.yml push frontend

      # Build and push the backend image
      - name: Build Backend Image
        run: |
          docker-compose -f docker-compose.yml build backend

      - name: Push Backend Image
        run: |
          docker-compose -f docker-compose.yml push backend
